//! Application Specific Data Packet (Type 30).
//!
//! These packets are used for application-specific communication between TCNet nodes.
//!
//! ## Resolume Arena ↔ Pro DJ Link Bridge (observed)
//!
//! The TCNet spec defines the outer Type 30 envelope, but the payload is application-defined.
//! From on-the-wire measurements, Arena and the Pro DJ Link Bridge use a simple 20-byte payload
//! with a 3-message challenge/response handshake.
//!
//! Payload (20 bytes):
//! - bytes 0..2: `step` (u16 LE): 0 = request/keepalive, 1 = bridge challenge, 2 = arena response
//! - bytes 2..4: `arena_port` (u16 LE): Arena's listener port (in range 65023-65535)
//! - bytes 4..8: `challenge` (u32 LE): generated by bridge (step=1), echoed by arena (step=2)
//! - bytes 8..12: `response` (u32 LE): `challenge XOR key` (key depends on opcode family)
//! - bytes 12..20: constant 8-byte trailer (observed): `0b48c85a9696a0fc`
//!
//! NOTE: The bridge's step=1 opcode varies per attempt and does not appear to affect the
//! response calculation; the 4-byte challenge is the value Arena responds to.

use crate::header::ManagementHeader;
use crate::types::{MessageType, NodeOptions, NodeType};

/// Resolume (registered application code `0x0ABC`) as observed in the 32-bit "Packet Signature"
/// field (little-endian on wire: `0000bc0a`).
pub const RESOLUME_SIGNATURE: u32 = 0x0abc_0000;

/// Observed constant trailer for Arena step=2 responses.
pub const RESOLUME_ARENA_TRAILER: [u8; 8] = [0x0b, 0x48, 0xc8, 0x5a, 0x96, 0x96, 0xa0, 0xfc];

/// Compute the XOR key for the Arena-style auth response.
///
/// The key is derived from the Resolume application signature and the local node's
/// IPv4 address using two independent FNV-1a (32-bit) hash chains XORed together:
///
///   xor_key = FNV-1a(sig_lo, sig_hi) ^ FNV-1a(ip[0], ip[1], ip[2], ip[3])
///
/// where `sig_lo`/`sig_hi` are the low/high bytes of `RESOLUME_SIGNATURE >> 16` (i.e. 0x0ABC),
/// and `ip` is the node's IPv4 address in network byte order.
pub fn compute_auth_xor_key(local_ip: std::net::Ipv4Addr) -> u32 {
    const FNV_OFFSET: u32 = 0x811C_9DC5;
    const FNV_PRIME: u32 = 0x0100_0193;

    #[inline]
    fn fnv1a(data: &[u8]) -> u32 {
        let mut h = FNV_OFFSET;
        for &b in data {
            h ^= b as u32;
            h = h.wrapping_mul(FNV_PRIME);
        }
        h
    }

    // Chain A: low 2 bytes of signature (0x0ABC → [0xBC, 0x0A])
    let sig = (RESOLUME_SIGNATURE >> 16) as u16;
    let chain_a = fnv1a(&sig.to_le_bytes());

    // Chain B: IPv4 address in network (big-endian) byte order
    let chain_b = fnv1a(&local_ip.octets());

    chain_a ^ chain_b
}

/// Application Specific Data packet.
#[derive(Debug, Clone)]
pub struct AppDataPacket {
    /// Common management header
    pub header: ManagementHeader,
    /// Data Identifier 1 (byte 24)
    pub data_id1: u8,
    /// Data Identifier 2 (byte 25)
    pub data_id2: u8,
    /// Data size
    pub data_size: u32,
    /// Total packets
    pub total_packets: u32,
    /// Packet number
    pub packet_no: u32,
    /// Packet signature
    pub signature: u32,
    /// Application data
    pub data: Vec<u8>,
}

impl AppDataPacket {
    fn resolume_arena_payload_step0(arena_port: u16) -> Vec<u8> {
        // step=0, arena_port, everything else zero
        let mut data = [0u8; 20];
        data[0..2].copy_from_slice(&0u16.to_le_bytes());
        data[2..4].copy_from_slice(&arena_port.to_le_bytes());
        data.to_vec()
    }

    fn resolume_arena_payload_step2(arena_port: u16, challenge: u32, xor_key: u32) -> Vec<u8> {
        // step=2, arena_port, echo challenge, response=challenge^key, trailer
        let mut data = [0u8; 20];
        data[0..2].copy_from_slice(&2u16.to_le_bytes());
        data[2..4].copy_from_slice(&arena_port.to_le_bytes());
        data[4..8].copy_from_slice(&challenge.to_le_bytes());

        let response = challenge ^ xor_key;
        data[8..12].copy_from_slice(&response.to_le_bytes());
        data[12..20].copy_from_slice(&RESOLUME_ARENA_TRAILER);
        data.to_vec()
    }

    /// Create a new Application Specific Data packet.
    pub fn new(
        node_id: u16,
        node_name: &str,
        sequence: u8,
        node_type: NodeType,
        node_options: NodeOptions,
        timestamp_us: u32,
        data_id1: u8,
        data_id2: u8,
        data: Vec<u8>,
    ) -> Self {
        Self::new_with_signature(
            node_id,
            node_name,
            sequence,
            node_type,
            node_options,
            timestamp_us,
            data_id1,
            data_id2,
            0,
            data,
        )
    }

    /// Create a new Application Specific Data packet with custom signature.
    pub fn new_with_signature(
        node_id: u16,
        node_name: &str,
        sequence: u8,
        node_type: NodeType,
        node_options: NodeOptions,
        timestamp_us: u32,
        data_id1: u8,
        data_id2: u8,
        signature: u32,
        data: Vec<u8>,
    ) -> Self {
        let header = ManagementHeader::new(
            node_id,
            MessageType::ApplicationData,
            node_name,
            sequence,
            node_type,
            node_options,
            timestamp_us,
        );

        Self {
            header,
            data_id1,
            data_id2,
            data_size: data.len() as u32,
            total_packets: 1,
            packet_no: 1,
            signature,
            data,
        }
    }

    /// Create an Arena-style step=0 request/keepalive.
    ///
    /// This is the packet Arena keeps broadcasting periodically (typically ~1s), and it triggers
    /// a bridge step=1 challenge when the bridge decides a (re)handshake is needed.
    pub fn resolume_arena_step0(
        node_id: u16,
        node_name: &str,
        sequence: u8,
        node_type: NodeType,
        node_options: NodeOptions,
        timestamp_us: u32,
        arena_port: u16,
    ) -> Self {
        Self::new_with_signature(
            node_id,
            node_name,
            sequence,
            node_type,
            node_options,
            timestamp_us,
            0xff, // Data Identifier 1
            0xff, // Data Identifier 2
            RESOLUME_SIGNATURE,
            Self::resolume_arena_payload_step0(arena_port),
        )
    }

    /// Create an Arena-style step=2 response.
    ///
    /// You must pass the 4-byte `challenge` that the bridge sent in its step=1 packet payload
    /// (bytes 4..8). Arena responds with `challenge XOR key` (bytes 8..12) plus a constant trailer.
    pub fn resolume_arena_step2(
        node_id: u16,
        node_name: &str,
        sequence: u8,
        node_type: NodeType,
        node_options: NodeOptions,
        timestamp_us: u32,
        arena_port: u16,
        challenge: u32,
        xor_key: u32,
    ) -> Self {
        Self::new_with_signature(
            node_id,
            node_name,
            sequence,
            node_type,
            node_options,
            timestamp_us,
            0xff, // Data Identifier 1
            0xff, // Data Identifier 2
            RESOLUME_SIGNATURE,
            Self::resolume_arena_payload_step2(arena_port, challenge, xor_key),
        )
    }

    /// Create Resolume-style subscription packets.
    /// Resolume sends TWO app data packets to subscribe to mixer updates.
    /// Returns a Vec of two packets that should both be sent.
    pub fn resolume_style_pair(
        node_id: u16,
        node_name: &str,
        sequence: u8,
        node_type: NodeType,
        node_options: NodeOptions,
        timestamp_us: u32,
    ) -> Vec<Self> {
        // Signature used by Resolume: 0x0abc0000 (little endian: 0000bc0a)
        let signature = RESOLUME_SIGNATURE;

        // Packet 1 data (20 bytes): 00002aff + zeros
        let data1 = vec![
            0x00, 0x00, 0xcf, 0xff,
            0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00,
        ];

        // Packet 2 data (20 bytes): 020099ff434797a41e0062c80b48c85a9696a0fc
        let data2 = vec![
            0x02, 0x00, 0x99, 0xff,
            0x43, 0x47, 0x97, 0xa4,
            0x1e, 0x00, 0x62, 0xc8,
            0x0b, 0x48, 0xc8, 0x5a,
            0x96, 0x96, 0xa0, 0xfc,
        ];

        vec![
            Self::new_with_signature(
                node_id,
                node_name,
                sequence,
                node_type,
                node_options,
                timestamp_us,
                0xff, // Data Identifier 1
                0xff, // Data Identifier 2
                signature,
                data1,
            ),
            Self::new_with_signature(
                node_id,
                node_name,
                sequence.wrapping_add(1), // Increment sequence for second packet
                node_type,
                node_options,
                timestamp_us,
                0xff, // Data Identifier 1
                0xff, // Data Identifier 2
                signature,
                data2,
            ),
        ]
    }

    /// Serialize the packet to bytes.
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut buf = Vec::with_capacity(42 + self.data.len());

        // Management header (bytes 0-23)
        buf.extend_from_slice(&self.header.to_bytes());

        // Data Identifier 1 & 2 (bytes 24-25)
        buf.push(self.data_id1);
        buf.push(self.data_id2);

        // Data Size (bytes 26-29)
        buf.extend_from_slice(&self.data_size.to_le_bytes());

        // Total Packets (bytes 30-33)
        buf.extend_from_slice(&self.total_packets.to_le_bytes());

        // Packet No (bytes 34-37)
        buf.extend_from_slice(&self.packet_no.to_le_bytes());

        // Packet Signature (bytes 38-41)
        buf.extend_from_slice(&self.signature.to_le_bytes());

        // Data (bytes 42+)
        buf.extend_from_slice(&self.data);

        buf
    }
}
